# 1. Source Code (load_digits)
***

In [2]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [10]:
# 데이터 준비
digits = load_digits()

# 데이터 구성 확인
print(dir(digits))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [58]:
# x_data 를 digits_data 에 지정
digits_data = digits.data

# x_data Test
print(digits_data.shape)
print(digits_data[0].reshape(8, 8))    # 이미지이므로 8 x 8 로 reshape 해주었다.
print()

# y_data 를 digits_label 에 지정
digits_label = digits.target

# y_data Test
print(digits_label.shape)
print(digits_label[:20])
print()

# Target Names 출력 (0 ~ 9 까지 10 개의 Class)
print(digits.target_names)

(1797, 64)
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]

(1797,)
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# data describe
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [28]:
# data split (train, test)
X_train, X_test, y_train, y_test = train_test_split(digits_data,
                                                    digits_label,
                                                    test_size=0.2,
                                                    random_state=10)

# split data Test
print('X_train 개수: {}  |  X_test 개수: {}'.format(len(X_train), len(X_test)))
print('y_train 개수: {}  |  y_test 개수: {}'.format(len(y_train), len(y_test)))

X_train 개수: 1437  |  X_test 개수: 360
y_train 개수: 1437  |  y_test 개수: 360


***
#### Decision Tree

In [29]:
from sklearn.tree import DecisionTreeClassifier
# Model 생성
decision_tree = DecisionTreeClassifier(random_state=32)

# training
decision_tree.fit(X_train, y_train)

# Prediction
y_pred = decision_tree.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        37
           1       0.83      0.88      0.86        34
           2       0.85      0.82      0.84        34
           3       0.80      0.90      0.85        40
           4       0.76      0.76      0.76        34
           5       0.91      0.91      0.91        32
           6       0.89      0.89      0.89        37
           7       0.95      0.90      0.92        40
           8       0.77      0.73      0.75        33
           9       0.85      0.87      0.86        39

    accuracy                           0.86       360
   macro avg       0.86      0.86      0.86       360
weighted avg       0.86      0.86      0.86       360



- precision 은 차례대로 [1.00, 0.83, 0.85, 0.80, 0.76, 0.91, 0.89, 0.95, 0.77, 0.85]
- recall 은 차례대로 [0.92, 0.88, 0.82, 0.90, 0.76, 0.91, 0.89, 0.90, 0.73, 0.87]
- 총 accuracy 는 0.86

***
#### Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
# Model 생성
random_forest = RandomForestClassifier(random_state=32)

# training
random_forest.fit(X_train, y_train)

# Prediction
y_pred = random_forest.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        37
           1       0.97      0.94      0.96        34
           2       0.92      1.00      0.96        34
           3       0.95      0.97      0.96        40
           4       0.94      0.94      0.94        34
           5       0.94      0.97      0.95        32
           6       1.00      1.00      1.00        37
           7       0.93      0.97      0.95        40
           8       0.97      0.88      0.92        33
           9       0.97      0.92      0.95        39

    accuracy                           0.96       360
   macro avg       0.96      0.96      0.96       360
weighted avg       0.96      0.96      0.96       360



- precision 은 차례대로 [1.00, 0.97, 0.92, 0.95, 0.94, 0.94, 1.00, 0.93, 0.97, 0.97]
- recall 은 차례대로 [0.97, 0.94, 1.00, 0.97, 0.94, 0.97, 1.00, 0.97, 0.88, 0.92]
- 총 accuracy 는 0.96

***
#### SVM

In [31]:
from sklearn import svm
# Model 생성
svm_model = svm.SVC()

# training
svm_model.fit(X_train, y_train)

# Prediction
y_pred = svm_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      1.00      0.99        34
           2       0.97      1.00      0.99        34
           3       1.00      0.97      0.99        40
           4       1.00      0.94      0.97        34
           5       0.97      1.00      0.98        32
           6       1.00      1.00      1.00        37
           7       1.00      1.00      1.00        40
           8       0.91      0.97      0.94        33
           9       1.00      0.95      0.97        39

    accuracy                           0.98       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360



- precision 은 차례대로 [1.00, 0.97, 0.97, 1.00, 1.00, 0.97, 1.00, 1.00, 0.91, 1.00]
- recall 은 차례대로 [1.00, 1.00, 1.00, 0.97, 0.94, 1.00, 1.00, 1.00, 0.97, 0.95]
- 총 accuracy 는 0.98

***
#### SGD Classifier

In [38]:
from sklearn.linear_model import SGDClassifier
# Model 생성
sgd_model = SGDClassifier()

# training
sgd_model.fit(X_train, y_train)

# Prediction
y_pred = sgd_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        37
           1       0.82      0.91      0.86        34
           2       0.97      1.00      0.99        34
           3       0.95      0.97      0.96        40
           4       0.89      0.91      0.90        34
           5       0.96      0.81      0.88        32
           6       1.00      0.97      0.99        37
           7       0.97      0.97      0.97        40
           8       0.81      0.88      0.84        33
           9       0.94      0.87      0.91        39

    accuracy                           0.93       360
   macro avg       0.93      0.93      0.93       360
weighted avg       0.93      0.93      0.93       360



- precision 은 차례대로 [1.00, 0.82, 0.97, 0.95, 0.89, 0.96, 1.00, 0.97, 0.81, 0.94]
- recall 은 차례대로 [0.97, 0.91, 1.00, 0.97, 0.91, 0.81, 0.97, 0.97, 0.88, 0.87]
- 총 accuracy 는 0.93

***
#### Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression
# Model 생성
logistic_model = LogisticRegression(solver='lbfgs', max_iter=3000)

# training
logistic_model.fit(X_train, y_train)

# Prediction
y_pred = logistic_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.91      0.91        34
           2       0.92      1.00      0.96        34
           3       0.97      0.95      0.96        40
           4       0.94      0.94      0.94        34
           5       0.94      0.94      0.94        32
           6       0.97      0.97      0.97        37
           7       0.97      0.95      0.96        40
           8       0.89      0.94      0.91        33
           9       1.00      0.92      0.96        39

    accuracy                           0.95       360
   macro avg       0.95      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



- precision 은 차례대로 [1.00, 0.91, 0.92, 0.97, 0.94, 0.94, 0.97, 0.97, 0.89, 1.00]
- recall 은 차례대로 [1.00, 0.91, 1.00, 0.95, 0.94, 0.94, 0.97, 0.95, 0.94, 0.92]
- 총 accuracy 는 0.95

***
#### Model 평가
- 5 개의 Model로 0 ~ 9 의 손글씨를 분류해보았습니다.
- 그 중 Decision Tree 의 accuracy 가 0.86 으로 가장 낮았고,
- SVM 의 accuracy 가 0.98 로 가장 높았습니다.
- Random Forest 는 0.96 으로 두 번째로 높은 accuracy 를 보여주었습니다.

#### sklearn.metrics
- 손글씨 분류기는 0 ~ 9 의 10 가지의 class 로 분류하는 모델입니다.
- 따라서, 0 이 아니지만, 0 으로 예측하는 경우(FP),
- 실제로 0 이지만, 0 이 아니라고 예측하는 경우(FN) 모두 중요하다고 생각되었습니다.
- 저는 위와 같은 이유로 모델 성능 측정 지표로 f1-score 를 선택하였고,
- f1-score 평균이 가장 높은 SVM 모델이 가장 성능이 좋았다고 생각합니다.
***

# 2. Source Code (load_wine)
***

In [50]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [51]:
# 데이터 준비
wines = load_wine()

# 데이터 구성 확인
print(dir(wines))

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']


In [64]:
# x_data 를 wine_data 에 지정
wine_data = wines.data
print(wine_data.shape)
print(wine_data[0])
print()

# y_data 를 wine_label 에 지정
wine_label = wines.target
print(wine_label.shape)
print(wine_label[0])
print()

# features 의 종류 확인 (wine 특징 13 features)
print(wines.feature_names)
print()

# label 의 종류 확인 (0, 1, 2 의 3 classes)
print(wines.target_names)

(178, 13)
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]

(178,)
0

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

['class_0' 'class_1' 'class_2']


In [65]:
# data describe
print(wines.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [66]:
# data split (train, test)
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                                    wine_label,
                                                    test_size=0.2,
                                                    random_state=10)

# split data Test
print('X_train 개수: {}  |  X_test 개수: {}'.format(len(X_train), len(X_test)))
print('y_train 개수: {}  |  y_test 개수: {}'.format(len(y_train), len(y_test)))

X_train 개수: 142  |  X_test 개수: 36
y_train 개수: 142  |  y_test 개수: 36


***
#### Decision Tree

In [67]:
from sklearn.tree import DecisionTreeClassifier
# Model 생성
decision_tree = DecisionTreeClassifier(random_state=32)

# training
decision_tree.fit(X_train, y_train)

# Prediction
y_pred = decision_tree.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94        18
           2       0.80      1.00      0.89         8

    accuracy                           0.94        36
   macro avg       0.93      0.96      0.94        36
weighted avg       0.96      0.94      0.95        36



- precision 은 차례대로 [1.00, 1.00, 0.80]
- recall 은 차례대로 [1.00, 0.89, 1.00]
- 총 accuracy 는 0.94

***
#### Random Forest

In [68]:
from sklearn.ensemble import RandomForestClassifier
# Model 생성
random_forest = RandomForestClassifier(random_state=32)

# training
random_forest.fit(X_train, y_train)

# Prediction
y_pred = random_forest.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94        18
           2       0.80      1.00      0.89         8

    accuracy                           0.94        36
   macro avg       0.93      0.96      0.94        36
weighted avg       0.96      0.94      0.95        36



- precision 은 차례대로 [1.00, 1.00, 0.80]
- recall 은 차례대로 [1.00, 0.89, 1.00]
- 총 accuracy 는 0.94

***
#### SVM

In [76]:
from sklearn import svm
# Model 생성
svm_model = svm.SVC()

# training
svm_model.fit(X_train, y_train)

# Prediction
y_pred = svm_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.70      0.78        10
           1       0.81      0.72      0.76        18
           2       0.42      0.62      0.50         8

    accuracy                           0.69        36
   macro avg       0.70      0.68      0.68        36
weighted avg       0.74      0.69      0.71        36



- precision 은 차례대로 [0.88, 0.81, 0.42]
- recall 은 차례대로 [0.70, 0.72, 0.62]
- 총 accuracy 는 0.69

***
#### SGD Classifier

In [82]:
from sklearn.linear_model import SGDClassifier
# Model 생성
sgd_model = SGDClassifier()

# training
sgd_model.fit(X_train, y_train)

# Prediction
y_pred = sgd_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.90      0.64        10
           1       0.85      0.61      0.71        18
           2       0.40      0.25      0.31         8

    accuracy                           0.61        36
   macro avg       0.58      0.59      0.55        36
weighted avg       0.65      0.61      0.60        36



- precision 은 차례대로 [0.50, 0.85, 0.40]
- recall 은 차례대로 [0.90, 0.61, 0.25]
- 총 accuracy 는 0.61

***
#### Logistic Regression

In [84]:
from sklearn.linear_model import LogisticRegression
# Model 생성
logistic_model = LogisticRegression(solver='lbfgs', max_iter=3000)

# training
logistic_model.fit(X_train, y_train)

# Prediction
y_pred = logistic_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94        18
           2       0.80      1.00      0.89         8

    accuracy                           0.94        36
   macro avg       0.93      0.96      0.94        36
weighted avg       0.96      0.94      0.95        36



- precision 은 차례대로 [1.00, 1.00, 0.80]
- recall 은 차례대로 [1.00, 0.89, 1.00]
- 총 accuracy 는 0.94

***
#### Model 평가
- 5 개의 Model로 0 ~ 2 의 3 가지 와인 클래스를 분류하는 모델을 작성해보았습니다.
- SGD Classifier 가 accuracy 0.61 로 가장 정확도가 낮았고,
- 그 중, 손글씨 분류에서 가장 좋은 성능을 보여주었던 SVM 모델의 accuracy 가 0.69 로 현저히 낮아졌습니다.
- SVM 모델이 데이터를 고차원으로 변환하는 과정에서 적은 수의 클래스가 오히려 역효과를 낸 것으로 보입니다.
- 반면, Decision Tree, Random Forest, Logistic Regression 의 accuracy 는 0.94 로 준수한 성능이었습니다.

#### sklearn.metrics
- 와인 분류 또한, 손글씨 분류와 마찬가지로 오차행렬에서의 구분과는 무관하게 전체적인 성능이 중요하다고 생각합니다.
- 따라서, 준수한 성능을 보여준 Decision Tree, Random Forest, Logistic Regression 모두 각각의 수치가 같으므로
- SVM, SGD Classifier 를 제외한 나머지 3 개의 모델이 성능이 좋았다고 생각합니다.
***

# 3. Source Code (load_breast_cancer)
***

In [85]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [86]:
# 데이터 준비
breast_cancer = load_breast_cancer()

# 데이터 구성 확인
print(dir(breast_cancer))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [88]:
# x_data 를 breast_cancer_data 에 지정
breast_cancer_data = breast_cancer.data
print(breast_cancer_data.shape)
print(breast_cancer_data[0])
print()

# y_data 를 breast_cancer_label 에 지정
breast_cancer_label = breast_cancer.target
print(breast_cancer_label.shape)
print(breast_cancer_label[0])
print()

# features 의 종류 확인 (breast_cancer 특징 30 개의 features)
print(breast_cancer.feature_names)
print()

# label 의 종류 확인 (0, 1 의 2 classes)
print(breast_cancer.target_names)

(569, 30)
[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]

(569,)
0

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']

['malignant' 'benign']


In [89]:
# data describe
print(breast_cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [90]:
# data split (train, test)
X_train, X_test, y_train, y_test = train_test_split(breast_cancer_data,
                                                    breast_cancer_label,
                                                    test_size=0.2,
                                                    random_state=10)

# split data Test
print('X_train 개수: {}  |  X_test 개수: {}'.format(len(X_train), len(X_test)))
print('y_train 개수: {}  |  y_test 개수: {}'.format(len(y_train), len(y_test)))

X_train 개수: 455  |  X_test 개수: 114
y_train 개수: 455  |  y_test 개수: 114


***
#### Decision Tree

In [92]:
from sklearn.tree import DecisionTreeClassifier
# Model 생성
decision_tree = DecisionTreeClassifier(random_state=32)

# training
decision_tree.fit(X_train, y_train)

# Prediction
y_pred = decision_tree.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.95      0.88        39
           1       0.97      0.89      0.93        75

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114



- precision 은 차례대로 [0.82, 0.97]
- recall 은 차례대로 [0.95, 0.89]
- 총 accuracy 는 0.91

***
#### Random Forest

In [93]:
from sklearn.ensemble import RandomForestClassifier
# Model 생성
random_forest = RandomForestClassifier(random_state=32)

# training
random_forest.fit(X_train, y_train)

# Prediction
y_pred = random_forest.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        39
           1       1.00      0.97      0.99        75

    accuracy                           0.98       114
   macro avg       0.98      0.99      0.98       114
weighted avg       0.98      0.98      0.98       114



- precision 은 차례대로 [0.95, 1.00]
- recall 은 차례대로 [1.00, 0.97]
- 총 accuracy 는 0.98

***
#### SVM

In [94]:
from sklearn import svm
# Model 생성
svm_model = svm.SVC()

# training
svm_model.fit(X_train, y_train)

# Prediction
y_pred = svm_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.82      0.88        39
           1       0.91      0.97      0.94        75

    accuracy                           0.92       114
   macro avg       0.93      0.90      0.91       114
weighted avg       0.92      0.92      0.92       114



- precision 은 차례대로 [0.94, 0.91]
- recall 은 차례대로 [0.82, 0.97]
- 총 accuracy 는 0.92

***
#### SGD Classifier

In [95]:
from sklearn.linear_model import SGDClassifier
# Model 생성
sgd_model = SGDClassifier()

# training
sgd_model.fit(X_train, y_train)

# Prediction
y_pred = sgd_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.77      0.85        39
           1       0.89      0.97      0.93        75

    accuracy                           0.90       114
   macro avg       0.91      0.87      0.89       114
weighted avg       0.91      0.90      0.90       114



- precision 은 차례대로 [0.94, 0.89]
- recall 은 차례대로 [0.77, 0.97]
- 총 accuracy 는 0.90

***
#### Logistic Regression

In [96]:
from sklearn.linear_model import LogisticRegression
# Model 생성
logistic_model = LogisticRegression(solver='lbfgs', max_iter=3000)

# training
logistic_model.fit(X_train, y_train)

# Prediction
y_pred = logistic_model.predict(X_test)

# confusion matrix and accuracy
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.97      0.94        39
           1       0.99      0.95      0.97        75

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114



- precision 은 차례대로 [0.90, 0.99]
- recall 은 차례대로 [0.97, 0.95]
- 총 accuracy 는 0.96

***
#### Model 평가
- 5 개의 Model로 0, 1의 2 클래스의 유방암 여부를 예측해보았습니다.
- 그 중, Random Forest 의 accuracy 가 0.98 로 가장 높게 측정되었습니다.
- 두 번째로는 Logistic Regression 이 accuracy 0.96 으로 높았습니다.
- SGD Classifier 는 0.90 의 accuracy 로 가장 성능이 낮게 측정되었습니다.

#### sklearn.metrics
- 유방암 여부를 예측하는 모델에서는 양성(positive)환자를 음성(negative)으로 측정하여서는 안됩니다.
- 따라서, FN(False Negative)를 최소화하여야 합니다.
- 이는 Precision 수치보다는 Recall 의 수치가 더 중요함을 의미합니다.
- Random Forest 는 Recall 수치와 accuracy 가 모두 0.98 로 아주 높게 측정되었으므로,
- Random Forest 모델이 유방암 여부 예측 모델로서 가장 적합하다고 사료됩니다.
***